version: "3.8"

# Define a network to set Docker images to in order for them to communicate with each other
networks:
  data-persistence:

services:
  database:
    container_name: ${DB_CONTAINER}
    image: ${DB_IMAGE}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./sql/init-scripts:/docker-entrypoint-initdb.d
    networks:
      - data-persistence
    ports:
      - 5432:5432
